# Generated by Django 3.1.7 on 2021-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='age',
            field=models.SmallIntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(default='something@mail.ru', max_length=254, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='login',
            field=models.CharField(default='a', max_length=40, unique=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='name',
            field=models.CharField(default='a', max_length=30, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='problematic',
            field=models.BooleanField(default=False, editable=False, verbose_name='Нарушения'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='surname',
            field=models.CharField(default='a', max_length=30, verbose_name='Фамилия'),
        ),
    ]
