# Generated by Django 3.1.7 on 2021-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0002_auto_20210803_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='age',
            field=models.SmallIntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='login',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='surname',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
    ]
