# Generated by Django 3.1.7 on 2021-08-07 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_auto_20210803_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='password',
            field=models.CharField(default='Придумайте надежный пароль', max_length=40, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, null=True, unique_for_date=True, verbose_name='Заголовок поста')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('datetime', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('amount_likes', models.SmallIntegerField(default=0, editable=False, verbose_name='Лайки')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='regform.registereduser', verbose_name='Автор')),
            ],
        ),
    ]
