# Generated by Django 3.1.7 on 2021-08-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0006_auto_20210808_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(default='Заголовок', max_length=40, verbose_name='Заголовок поста'),
        ),
    ]
