# Generated by Django 3.1.7 on 2021-08-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0007_auto_20210808_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['datetime'], 'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователя'},
        ),
    ]
