# Generated by Django 3.1.7 on 2021-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0008_auto_20210808_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
