# Generated by Django 3.1.7 on 2021-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0012_remove_registereduser_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='custom_url',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Пользовательский url'),
        ),
    ]
