# Generated by Django 3.1.7 on 2021-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0013_registereduser_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='custom_url',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Пользовательский url'),
        ),
    ]
