# Generated by Django 3.1.7 on 2021-08-22 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0014_auto_20210816_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='custom_url',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Пользовательский url обязан иметь хотя бы одну букву', regex='^(?=.*[a-zA-Z])')], verbose_name='Пользовательский url (по желанию)'),
        ),
    ]
