# Generated by Django 3.1.7 on 2021-08-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0016_auto_20210823_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_type', models.SmallIntegerField(blank=True, null=True, verbose_name='Лайк - 0, коммент - 1')),
                ('react_time', models.DateTimeField(auto_now=True, verbose_name='Время появления реакции')),
                ('from_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regform.userpost', verbose_name='Пост с реакциями')),
            ],
        ),
    ]
