# Generated by Django 3.1.7 on 2021-08-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0017_postreact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreact',
            name='from_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regform.userpost', verbose_name='Пост с реакциями'),
        ),
    ]
