# Generated by Django 3.1.7 on 2021-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0018_auto_20210825_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreact',
            name='reacted_user_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Юзер который реагирует'),
        ),
    ]
