# Generated by Django 3.2.7 on 2021-09-05 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Логин')),
                ('password', models.CharField(default='Придумайте надежный пароль', max_length=40, verbose_name='Пароль')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('fathers_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('age', models.SmallIntegerField(blank=True, verbose_name='Возраст')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('problematic', models.BooleanField(default=False, editable=False, verbose_name='Нарушения')),
                ('custom_url', models.SlugField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Пользовательский url обязан иметь хотя бы одну букву', regex='^(?=.*[a-zA-Z])')], verbose_name='Пользовательский url (по желанию)')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Заголовок', max_length=40, verbose_name='Заголовок поста')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('amount_likes', models.SmallIntegerField(default=0, editable=False, verbose_name='Лайки')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Переезд.registereduser', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост пользователя',
                'verbose_name_plural': 'Посты пользователя',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='PostReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('react_type', models.SmallIntegerField(blank=True, null=True, verbose_name='Лайк - 0, коммент - 1')),
                ('react_time', models.DateTimeField(auto_now=True, verbose_name='Время появления реакции')),
                ('reacted_user_id', models.SmallIntegerField(blank=True, null=True, verbose_name='Юзер который реагирует')),
                ('from_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Переезд.userpost', verbose_name='Пост с реакциями')),
            ],
        ),
    ]
