# Generated by Django 3.2.7 on 2021-09-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Переезд', '0003_alter_registereduser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreact',
            name='reacted_user_id',
        ),
        migrations.AddField(
            model_name='postreact',
            name='reacted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Переезд.registereduser', verbose_name='Юзер который реагирует'),
        ),
    ]
